### ISSUE TITLE
의료진 도메인 기능 리팩토링

### ISSUE THREAD

**Issue by 2dongyeop** [HBNU-Avocado/Avocado-backend-with-hexagonal#8]
## Description 🔍
의료진 도메인 기능을 개발합니다.

<br/>

## Todo 🗓️
- [x] 의료진 단건 조회
- [x] 의료진 목록 조회
- [x] 의료진 비밀번호 변경
- [x] 의료진 정보 수정
- [ ] 의료진 탈퇴
- [ ] 자신이 속한 병원의 리뷰 목록 조회
- [ ] 자신이 댓글을 작성한 게시글 목록 조회

<br/>

## Etc

<br/>
